version: '2'

services:
  dockertoolsperf:
    image: weidazhao/dockertoolsperf:Debug
    environment:
      - REMOTE_DEBUGGING=${REMOTE_DEBUGGING}
    ports:
      - "80:80"
    volumes:
      - .:/app
