FROM microsoft/dotnet:1.0.0-core

# Set the Working Directory
WORKDIR /app

# Configure the listening port to 80
ENV ASPNETCORE_URLS http://*:80
EXPOSE 80

# Keep the container alive
ENTRYPOINT ["/bin/bash", "-c", "tail -f /dev/null"]
