version: '2'

services:
  dockertoolsperf:
    image: microsoft/dotnet:1.0.0-core
    labels:
      - "com.microsoft.visualstudio.devcontainer"
    environment:
      - DOTNET_PACKAGES_CACHE=/dotnet_packages
      - REMOTE_DEBUGGING=${REMOTE_DEBUGGING}
    volumes:
      - .:/app
      - ~/.nuget/packages:/dotnet_packages:ro
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
