version: '2'

services:
  dockertoolsperf:
    build:
      args:
        source: obj/dummy-folder-for-docker-build
    labels:
      - "microsoft.aspnetcore.developmentcontainer"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - .:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
