version: '2'

services:
  dockertoolsperf:
    image: weidazhao/dockertoolsperf:Debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    environment:
      - REMOTE_DEBUGGING=${REMOTE_DEBUGGING}
      - DOTNET_PACKAGES_CACHE=/dotnet_packages
      - APP_ASSEMBLY=/app/bin/Debug/netcoreapp1.0/DockerToolsPerf.dll
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ~/.nuget/packages:/dotnet_packages:ro
      - ~/clrdbg:/clrdbg:ro